name: Github Action Demo
run-name: ${{ github.actor }} is testing out Github actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
                example-command "$super_secret"





